### ISSUE TITLE
non-ascii in DESCRIPTION.rst

### ISSUE THREAD

**Issue by TomGoBravo** [scottkmaxwell/pbjson#1]
I tried to install pbjson on a server which probably has some ancient version of the python tools. installing failed with error 
```
       LONG_DESCRIPTION = f.read()
              File "/srv/venvs/service/trusty/service_venv_python3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
                   return codecs.ascii_decode(input, self.errors)[0]
                 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4528: ordinal not in range(128)
```
Looking at https://github.com/scottkmaxwell/pbjson/commits/master/DESCRIPTION.rst I found 3 non-ascii characters in these quotes `Let’s break that out` and `Since ‘code’ was`. https://github.com/scottkmaxwell/pbjson/commit/75fc9b54ce357a1f4ff15b705b6375c8d4d4c0b1#diff-9bafad465c7c8135c979e1e45c1e9102 suggests there is precedence for preferring ascii. Please modify the text file or the code that decodes it. Thank you!

**Comment by scottkmaxwell** [comment]
I just noticed this and fixed it.
