### ISSUE TITLE
Format of float number.

### ISSUE THREAD

**Issue by n3tricks** [scottkmaxwell/pbjson#4]
Good day.

I'm having trouble understanding float number formatting. According to the documentation, the number 4.5 should be represented as 0x624012, which corresponds to the binary representation of this number in double format. However, pbjson 1.15 formats it differently:
```
>>> binascii.hexlify(pbjson.dumps(4.5))
b'624d5d'
```
Is this a bug of the library or an documentation mistake?

**Comment by scottkmaxwell** [comment]
Thanks. Documentation updated.
