### ISSUE TITLE
Update needed to support python 3.10

### ISSUE THREAD

**Issue by tramora** [scottkmaxwell/pbjson#6]
Hi @scottkmaxwell and thank you for your lib.

I'm using it successfully under `python3.8` but I'd like to upgrade (python3.8 end of life is 2024-10).

Unfortunately pbjson is no longer compatible with `python3.10`. 

There may be other problems but the first I met is that the class `Mapping` it depends on is no longer in the `collections` package but in `collections.abc`.

Is there any chance you adapt the import to handle both version<3.10 and version>=3.10 ? Thanks a lot.

**Comment by scottkmaxwell** [comment]
I released pbjson 1.18.0 a couple of weeks ago. It should work fine on Python 3.10 and Python 3.11. It also publishes the `pbjson` tool into your virtual environment.

**Comment by tramora** [comment]
Thanx @scottkmaxwell ! Sorry that I missed your fix (my version was frozen).
