### ISSUE TITLE
memory leak when reading data

### ISSUE THREAD

**Issue by janpetto** [scottkmaxwell/pbjson#7]
I have a binary file which contains many entries generated by pbjson at some previous point in time. These entries are independent from another and are simply length encoded and concatenated in the file. When I read the file and decode the entries using `pbjson.loads()`, memory does not get freed correctly. The behaviour can be reproduced using the following program:

```python
# memory.py
import pbjson

entry = pbjson.dumps("Hello World")  # some example entry
entry_len = len(entry)


def write():
    n = 1000000
    with open("dump.bin", "wb") as file:
        for _ in range(n):
            file.write(entry)
    print("wrote %d entries" % n)


def read():
    n = 0
    with open("dump.bin", "rb") as file:
        while data := file.read(entry_len):
            pbjson.loads(data)
            n += 1
    print("read %d entries" % n)


if __name__ == "__main__":
    write()
    read()
```

This produces a `dump.bin` file which is approx. 11MiB of size and then reads it again. When running this code with the [memory_profiler](https://github.com/pythonprofilers/memory_profiler) module the memory leak is clearly visible, the loading of the data consumes more than 40 MiB of RAM:

```mprof run -T 0.01 memory.py```
![with_pbjson](https://github.com/scottkmaxwell/pbjson/assets/6023552/6a7e2ba2-c387-4aa6-8f9a-afdd79597fbe)

If I remove the `pblson.loads(data)` line, the code does not leak memory:
![no_pbjson](https://github.com/scottkmaxwell/pbjson/assets/6023552/181ffd78-4b2d-4f8b-9b9c-47167ae8f19e)

I cannot use the `pbjson.load(fp)` method, because in my real application scenario the data file is very large and gets streamed to the program, also the actual data entries are of course more complex and of different sizes. But I suspect the problem would be the same, as the `load(fp)` method simply reads the entire file and then performs the same decode operation.

Am I doing something wrong here, or is there indeed a memory leak?

**Comment by scottkmaxwell** [comment]
Nice analysis, thank you. If you use the standard json module instead of pbjson, do you see something similar? I used that as a starting point. I won’t have time to look at this immediately but this could at least confirm that the problem is in the modifications I made rather than in the original code.

**Comment by Edgxxar** [comment]
using the default `json` module and opening the file in text mode I don't see any memory leak. But of course the files get larger and it also takes almost twice as long to execute.

Thanks for developing this awesome module btw, I'm using `orjson` for the moment, which at least eliminates the performance problem, but naturally is not as space efficient.

**Comment by scottkmaxwell** [comment]
I have reproduced your results. As a short term fix until I an dig into it, you can disable the C speedups:
```
pbjson._toggle_speedups(False)
```

**Comment by scottkmaxwell** [comment]
Fixed!

**Comment by scottkmaxwell** [comment]
It turns out I just needed to add a `PyBuffer_Release` at the end of `py_decode`.
